# .streamlit/secrets.toml

# Gemini API key
# To get a Gemini API key:
# 1. Go to https://makersuite.google.com/app/apikey
# 2. Sign in with your Google account
# 3. Click "Create API key"
# 4. Copy the API key and paste it below
# 5. Restart the Streamlit application

# Replace the value below with your actual Gemini API key
GEMINI_API_KEY = "your-api-key-here"

# IMPORTANT: Do not commit this file to version control!
# The .streamlit folder should be in your .gitignore file.
